# Documentation on this file structure: https://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  -
    id: trident-client
    main: ./cmd/trident-client/main.go
    binary: trident-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  -
    id: trident-nozzle
    main: ./cmd/trident-nozzle/main.go
    binary: trident-nozzle
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  # skip changelog generation for now
  skip: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

